### ISSUE TITLE
AutoFac 4.0.0 upgrade

### ISSUE THREAD

**Issue by ZodiacZA** [Particular/NServiceBus.Autofac#3]
With AutoFac 4.0.0-rc1 released, might want to look at supporting the new version.

This has been in development for over 6 months so has reached a level of stability.

**Comment by SimonCropp** [comment]
@ZodiacZA we try to avoid taking unstable upstream dependencies. It has bitten us before since those upstream dependencies are still free to make breaking changes.

if you wish to use AutoFac 4.0.0-rc1 in your solution then you can do a nuget update on autofac 

    Update-Package autofac -IncludePrerelease 

The reason this works is that (currently) the subset of Autofac APIs used by NSB are unchanged between autofac v3 and v4.

Dont forget you will also need a binding redirect

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
