### ISSUE TITLE
Update to Autofac >= 4.2.1 without the obsolete warning

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/NServiceBus.Autofac#36]
The last release of Autofac obsoleted the `ContainerBuilder.Update` method - which we use.

We need to change the way we handle our container reference to enable us to reference the `ContainerBuilder` instead of the `Container`.

We should also then update our docs samples to include an example of how we suggest our customers can work with our container registration code in conjunction with not using `ContainerBuilder.Update`.

**Comment by WilliamBZA** [comment]
Implementing the change to pass a `ContainerBuilder` instead of the `ILifetimeScope` is a potential major performance bottleneck. Autofac restricts the invocation of `ContainerBuilder.Build()` to once per instance of `ContainerBuilder`, which means we would need to reconstruct the entire `ContainerBuilder` after each update.

This also has the possibility of introducing some rather convoluted logic around dealing with singleton registrations and making sure the instances are copied through correctly to the new builders.

**Comment by adamralph** [comment]
@WilliamBZA is it right to assume that the obsolete API will be removed in 5.0.0? If so, do you know if there is an ETA for 5.0.0?

**Comment by WilliamBZA** [comment]
@adamralph 

> The plan is to leave them obsolete for a year or more, weaning developers off the use of `Update`, and in a future major release remove the methods altogether.

https://github.com/autofac/Autofac/issues/811

It's not final yet, there's still discussion on the topic from the Autofac side.

I worry though that this is going to be a direction that containers take in general and we'll have more containers adopting this stance in future releases. If that happens we will have to change the way we consume containers. I'm raising an issue in platdev related to this as it is a long-term problem that we do need a solution for (and perhaps switch to a Pure DI approach).

**Comment by WilliamBZA** [comment]
Revising to a medium for now. This is not a small.

**Comment by WilliamBZA** [comment]
@scrooby Do you mind if I ask what you wanted to do with the instance of `IEndpointInstance` once it was registered in the container?

**Comment by WilliamBZA** [comment]
https://github.com/Particular/NServiceBus.Autofac/pull/37 Has been merged. Closing this issue.

**Comment by scrooby** [comment]
@WilliamBZA Originally we needed this because we registered an event handler to the `MessgaeSentToErrorQueue` event which resolved out another class to do the heavy lifting. The class then constructor injected the `IEndpointInstance` so it could publish events out. However, looking at the code again, a simpler approach would just be to new up an instance of this class, and pass in the `IEndpointInstance` I have in my startup code, avoiding the container all together.

**Comment by boblangley** [comment]
@scrooby That is the best approach.

It looks like for us to avoid the `Update` method means the container you pass in cannot be updated, even using a `ContainerBuilder`. We are forced to copy the container registrations into a new `ContainerBuilder` ourselves and use that until we are ready to `Build` at startup, afterwhich we use that internal container, not the one passed in by the user.

We cannot share a `ContainerBuilder` either, because either NServiceBus or the user calling `Build` means the other cannot obtain a copy of the updated container.

So we are not releasing a new version of this library for now, which will allow any customers that currently rely on `Update` to continue doing so.
