### ISSUE TITLE
Autofac : Registering a module through XML doesn't set the property of that Module.

### ISSUE THREAD

**Issue by AadeshPaygude** [Particular/NServiceBus.Autofac#41]
I have following XML for registering a module "**AutofacProject.AutoFacModule**". I want to set a property "**PropertyValue**" using the xml but it's not working as expected. I could not find samples for Autofac module registration using xml file on internet.

```
<autofac>
     <modules>
              <module type="AutofacProject.AutoFacModule, AutofacProject">
                      <properties>
                                 <property name="PropertyValue" value ="true"/>
                      </properties>
              </module>
     </modules>
</autofac>

```

**Comment by adamralph** [comment]
@AadeshPaygude this sounds like a general Autofac question rather than anything specifically to NServiceBus.Autofac. Have you tried asking in a more general forum, e.g. StackOverflow?

If, however, you can use this feature successfully outside an NServiceBus project, but unsuccessfully inside one, then that suggest a problem with NServiceBus.Autofac, and we'd be certain to look into that.

**Comment by AadeshPaygude** [comment]
Hey sorry, the query was more generic related to Autofac and also has been resolved. so closing this thread.

**Comment by adamralph** [comment]
Thanks for the update @AadeshPaygude
